# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexPageCarousel', models.BooleanField(default=False, help_text='Decide whether or not this image will be included in the Home Page Carousel', verbose_name='Carousel')),
                ('imageGallery', models.BooleanField(default=False, help_text='Decide whether or not this image will be shown in the gallery', verbose_name='Gallery')),
                ('studentGallery', models.BooleanField(default=False, help_text="Decide whether or not this image will be shown in the Student's Corner", verbose_name='StudentsCorner')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='photologue.Photo')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
