# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20170722_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextended',
            name='studentGallery',
            field=models.BooleanField(default=False, help_text="Decide whether or not this image will be shown in the Student's Corner", verbose_name='StudentsCorner'),
        ),
    ]
