# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_photoextended_studentgallery'),
        ('basic', '0002_auto_20170727_1902'),
    ]

    operations = [
    ]
