# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180512_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='committee',
        ),
        migrations.AddField(
            model_name='people',
            name='institute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
