# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-27 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180527_2257'),
        ('people', '0005_auto_20180526_0433'),
    ]

    operations = [
    ]
