# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_merge_20180528_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='link_fb',
            field=models.URLField(blank=True, default='#', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='link_gs',
            field=models.URLField(blank=True, default='#', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='link_ln',
            field=models.URLField(blank=True, default='#', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='link_tw',
            field=models.URLField(blank=True, default='#', max_length=400, null=True),
        ),
    ]
