# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180612_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='link_fb',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='link_gh',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='link_gs',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='link_ln',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='link_tw',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
