# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20180617_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='academic_qualifications',
            field=models.TextField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='institute',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='office',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='professional_memberships',
            field=models.TextField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='publications',
            field=models.TextField(blank=True, max_length=300000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
