# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 13:00
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(max_length=20000)),
                ('file', models.FileField(upload_to=b'careers/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'title', unique=True)),
            ],
            options={
                'ordering': ('-start_date',),
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
