# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='linkage_images/')),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Linkage',
                'verbose_name_plural': 'Linkages',
            },
        ),
    ]
