# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkages',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
