# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkages', '0002_auto_20180526_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkages',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
