# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 10:15
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170709_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
