# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 19:37
from __future__ import unicode_literals

import basic.utils
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=basic.utils.get_today_start)),
                ('end_date', models.DateTimeField(default=basic.utils.get_today_end)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
