# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
