#!/usr/bin/env python

import os
import sys
import django.core.wsgi
from distutils.sysconfig import get_python_lib

# GETTING-STARTED: make sure the next line points to your settings.py:
os.environ['DJANGO_SETTINGS_MODULE'] = 'odyssy.settings'
# GETTING-STARTED: make sure the next line points to your django project dir:
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi',
                'odyssy'))
os.environ['PYTHON_EGG_CACHE'] = get_python_lib()

application = django.core.wsgi.get_wsgi_application()
