# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_structure', models.ImageField(upload_to=b'fee_structure/')),
            ],
        ),
    ]
