# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
