# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admission_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='programme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
