# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Sample Name', max_length=30)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2017, 5, 24, 0, 20, 11, 684825))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2017, 5, 24, 0, 20, 11, 684877))),
                ('description', models.TextField(max_length=300)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
