# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'verbose_name': 'Tender', 'verbose_name_plural': 'Tenders'},
        ),
        migrations.AddField(
            model_name='tender',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
