# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
