# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0002_auto_20180703_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='speaker',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
