# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0003_talk_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, max_length=90000, null=True),
        ),
    ]
