# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('btech', 'Bachelor of Technology'), ('mtech', 'Master of Technology')], default='btech', max_length=120)),
                ('branch', models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('it', 'Information Technology'), ('both', 'Computer Science & Engineering and Information Technology')], default='cse', max_length=120)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('lecture', models.IntegerField(default=0)),
                ('tutorial', models.IntegerField(default=0)),
                ('practical', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('text_book', models.TextField(blank=True, max_length=120, null=True)),
                ('ref_book', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ('code',),
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseInSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Course')),
            ],
            options={
                'ordering': ('semester',),
                'verbose_name': 'CourseInSem',
                'verbose_name_plural': 'CoursesInSems',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.PositiveIntegerField(default=1)),
                ('structure_btech_it', models.TextField(blank=True, max_length=20000, null=True)),
                ('structure_btech_cs', models.TextField(blank=True, max_length=20000, null=True)),
                ('structure_mtech_cs', models.TextField(blank=True, max_length=20000, null=True)),
            ],
            options={
                'ordering': ('sem',),
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.AddField(
            model_name='courseinsem',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Semester'),
        ),
    ]
