# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
