# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20180515_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Programme'),
        ),
    ]
