# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20180516_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinsem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseinsem',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester II'), ('3', 'Semester III'), ('4', 'Semester IV'), ('5', 'Semester V'), ('6', 'Semester VI'), ('7', 'Semester VII'), ('8', 'Semester VII1')], default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='programme',
            name='branch_code',
            field=models.CharField(blank=True, help_text='e.g. CSE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Unique code e.g. CSE101', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. B.Tech', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CourseInSem',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
