# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20180608_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='calenders/')),
                ('name', models.TextField(blank=True, default='ac', max_length=1000, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Academic Calender',
                'verbose_name_plural': 'Academic Calenders',
            },
        ),
    ]
