# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ('-date',), 'verbose_name': 'Academic Calender', 'verbose_name_plural': 'Academic Calenders'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.TextField(blank=True, default='ac', max_length=1000, null=True, unique=True),
        ),
    ]
