# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_auto_20180612_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(default='slug', null=True),
        ),
    ]
