# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_calendar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
