# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ('name',), 'verbose_name': 'Institute', 'verbose_name_plural': 'Institute'},
        ),
    ]
