# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(choices=[('default', 'Select choice'), ('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Member', 'Member'), ('Member Secretary', 'Member Secretary')], default='default', max_length=20)),
                ('origin', models.CharField(max_length=150)),
                ('committee', models.CharField(choices=[('default', 'Select choice'), ('finance', 'Finance Committee'), ('building-works', 'Building And Works Committee'), ('hr-planning', 'HR Planning Committee'), ('research-council', 'Research Council'), ('strategic-planning', 'Strategic Planning Committee')], default='default', max_length=30)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institute',
            },
        ),
    ]
