# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ('name',), 'verbose_name': 'Committee', 'verbose_name_plural': 'Committees'},
        ),
    ]
